package greendao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ELEVE.
 */
public class Eleve {

    private Long id;
    private String Nom;
    private String Prenom;

    // KEEP FIELDS - put your custom fields here
    private boolean check;
    // KEEP FIELDS END

    public Eleve() {
    }

    public Eleve(Long id) {
        this.id = id;
    }

    public Eleve(Long id, String Nom, String Prenom) {
        this.id = id;
        this.Nom = Nom;
        this.Prenom = Prenom;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNom() {
        return Nom;
    }

    public void setNom(String Nom) {
        this.Nom = Nom;
    }

    public String getPrenom() {
        return Prenom;
    }

    public void setPrenom(String Prenom) {
        this.Prenom = Prenom;
    }

    // KEEP METHODS - put your custom methods here

    public boolean isCheck() {
        return check;
    }

    public void setCheck(boolean check) {
        this.check = check;
    }
    // KEEP METHODS END

}
